{application,gwebdev,
             [{description,"gwebdev"},
              {vsn,"1"},
              {modules,[base_dtl,gwebdev,gwebdev_app,gwebdev_resource,
                        gwebdev_sup]},
              {registered,[]},
              {applications,[kernel,stdlib,inets,crypto,mochiweb,webmachine]},
              {mod,{gwebdev_app,[]}},
              {env,[]}]}.
